---
kind: List
apiVersion: v1
items:
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: playground
      namespace: celery-jobq
    rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["list"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: playground
      namespace: celery-jobq
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: celery-jobq
    roleRef:
      kind: ClusterRole
      name: playground
      apiGroup: rbac.authorization.k8s.io
  - kind: Pod
    apiVersion: v1
    metadata:
      name: playground
      labels:
        app: celery-jobq
      namespace: celery-jobq
    spec:
      containers:
        - name: playground
          image: aleozlx/k8sapi-playground
